services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose:
      - 27017
      
  room_collector:
    build: ./room_collector
    ports:
      - "5001:5001"
    depends_on:
      - "mongodb"

  room_api:
    ports:
      - "5002:5002"
    build: ./room_api
    depends_on:
      - "mongodb"

  # room_ui:
  #   build: ./room_ui
  #   ports:
  #     - 8501:8501
  #   depends_on:
  #     - "room_collector"
  #     - "room_api"