services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
      
  room_collector:
    build: ./room_collector
    depends_on:
      - "mongodb"

  room_api:
    ports:
      - "5002:5002"
    build: ./room_api
    depends_on:
      - "mongodb"

  room_ui:
    build: ./room_ui
    depends_on:
      - "room_collector"
      - "room_api"